config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'consulting', to: 'pages#consulting'
  get 'atelier', to: 'pages#atelier'
  get 'collaboration', to: 'pages#collaboration'
  get 'creation', to: 'pages#creation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('https://res.cloudinary.com/diavcbwzh/image/upload/v1606245809/Noa%20Bakery/WhatsApp_Image_2020-11-24_at_17.04.03_iarwpu.jpg') %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Noa Katz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:white;">
    <%= yield %>
  </body>
</html>

app/views/pages/atelier.html.erb
<div class="container">
  <div class="logo-atelier">
    <%= cl_image_tag('https://res.cloudinary.com/diavcbwzh/image/upload/v1606245824/Noa%20Bakery/WhatsApp_Image_2020-11-24_at_17.02.58_uap6hy.jpg')%>
  </div>
  <%= render 'shared/navbar' %>
</div>

app/views/pages/consulting.html.erb
<div class="container">
  <div class="logo-home">
    <%= cl_image_tag('https://res.cloudinary.com/diavcbwzh/image/upload/v1606245817/Noa%20Bakery/WhatsApp_Image_2020-11-24_at_17.02.59_ik70be.jpg')%>
  </div>
  <%= render 'shared/navbar' %>
  <div class="main-navigation">
    <div class="col-12 col-lg-3">
      <div class="avatar-consulting">
        <%= image_tag "LMP.jpg"%>
      </div>
       <div id="consulting-text">
          <br>
          <p>Je vous accompagne dans la création d’une carte de desserts et la formation de votre équipe.
            <br>
            <br>
            Parlons-en !</p>
        </div>
    </div>
    <div class="col-12 col-lg-9">
      <iframe src="https://forms.monday.com/forms/embed/a4eb8c31d124ba702e87d5ef2a0459ba?r=use1" width="100%" height="500" style="border: 0;"></iframe>
    </div>

    </div>
    <%= render 'shared/footer' %>
  </div>

app/views/pages/creation.html.erb
<div class="container">
  <div class="logo-creation">
    <%= cl_image_tag('https://res.cloudinary.com/diavcbwzh/image/upload/v1606245812/Noa%20Bakery/WhatsApp_Image_2020-11-24_at_17.04.02_o0x0ap.jpg')%>
  </div>
  <%= render 'shared/navbar' %>

<div class='embedsocial-instagram' data-ref="6d3e5ebca6051654aac10134b8f1bbc625cd29db"></div><script>(function(d, s, id){var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/embedscript/in.js"; d.getElementsByTagName("head")[0].appendChild(js);}(document, "script", "EmbedSocialInstagramScript"));</script>

</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="logo-home">
      <%= image_tag "bakery.png"%>
    </div>
</div>
  <%= render 'shared/navbar' %>
  <div class="main-navigation">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-3">
        <div class="avatar">
          <%= image_tag "candice.jpg", crop: :fill, class:"avatar" %>
        </div>
      </div>
      <div class="col-12 col-lg-9">
          <div id="about-me">
            <br>
            <p>Passionnée de pâtisserie depuis mon plus jeune âge et diplômée d’une école de commerce et
              d’une école de pâtisserie, je décide de faire de ma passion mon métier.
              <br>
              <br>
              Formée par Cyril Lignac et Benoit Couvrand et consultante pour l’émission Le Meilleur
              Pâtissier deux années consécutives, j’ai le plaisir de partager mon savoir-faire à travers mes
              différentes activités.</p>
          </div>
      </div>
    </div>
</div>
  <%= render 'shared/footer' %>
</div>

app/views/pages/photography.html.erb
photography.html.erb

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="col-9 col-lg-6">
    <ul class="footer-links">
      <li>
        <%= link_to image_tag("instagram.png"), "https://www.instagram.com/noakatzbakery/", class: "icons", target: :_blank %>
      </li>
      <li>
        <%= link_to image_tag("facebook.png"), "https://www.facebook.com/NoaKatzBakery/", class: "icons", target: :_blank %>
      </li>
      <li>
        <%= link_to image_tag("email.png"), "mailto:noa@noakatzbakery.com", class: "icons", target: :_blank %>
      </li>
    </ul>
  </div>
  <div class="col-3 col-lg-6">
    <div id="copyright">
      <p>Copyright 2021</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="buttons">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <li><%= link_to "Accueil", root_path, class: "btn-navbar text-decoration-none" %></li>
      </li>
      <li class="nav-item">
        <li><%= link_to "Consulting", consulting_path, class: "btn-navbar text-decoration-none" %></li>
        <li><%= link_to "Atelier", atelier_path, class: "btn-navbar text-decoration-none" %></li>      <li><%= link_to "Collaboration", collaboration_path, class: "btn-navbar text-decoration-none" %></li>
        <li><%= link_to "Creation", creation_path, class: "btn-navbar text-decoration-none" %></li>
      </li>
    </ul>
  </div>
  </ul>
</div>
</div>